# Generated by Django 4.0.5 on 2022-07-30 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='screenShot',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('serverName', models.CharField(max_length=15)),
                ('shiftTime', models.CharField(max_length=50)),
                ('startingCountScreenShot', models.ImageField(default='', null=True, upload_to='startingScreenShot')),
                ('endingCountScreenShot', models.ImageField(default='', null=True, upload_to='endingingScreenShot')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='serverSheet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('serverName', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=50)),
                ('shiftTime', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('startingCount', models.IntegerField(blank=True, null=True)),
                ('endingCount', models.IntegerField(blank=True, null=True)),
                ('teamName', models.CharField(blank=True, max_length=50, null=True)),
                ('isghosted', models.CharField(blank=True, default='yes', max_length=50, null=True)),
                ('isbonus', models.CharField(blank=True, max_length=50, null=True)),
                ('commentText', models.CharField(default='', max_length=500)),
                ('approval', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('balanceCheck', models.CharField(blank=True, default='no', max_length=10, null=True)),
                ('startingCountScreenShot', models.ImageField(default='', null=True, upload_to='startingScreenShot')),
                ('endingCountScreenShot', models.ImageField(default='', null=True, upload_to='endingingScreenShot')),
                ('slug', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='shiftAllotment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('serverName', models.CharField(max_length=15)),
                ('shiftTime', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(default=0)),
                ('teamName', models.CharField(max_length=20)),
                ('dateOfBirth', models.CharField(max_length=30)),
                ('profilePic', models.ImageField(upload_to='profilePic')),
                ('idProof', models.ImageField(upload_to='idProof')),
                ('pass1', models.CharField(max_length=40)),
                ('pass2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='balanceHistory',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('lastPaymentDate', models.CharField(max_length=50)),
                ('weekNormal', models.CharField(max_length=15)),
                ('weekBonus', models.CharField(max_length=15)),
                ('weekGhosted', models.CharField(max_length=15)),
                ('weekBalance', models.CharField(max_length=15)),
                ('checkerUsername', models.CharField(max_length=50)),
                ('commentText', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
