# Generated by Django 4.0.5 on 2022-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='userName',
            field=models.CharField(max_length=40),
        ),
    ]
