# Generated by Django 4.0.5 on 2022-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_serversheet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
